# Generated by Django 4.1.6 on 2023-03-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='fileField',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='img',
        ),
    ]
