# Generated by Django 4.1.6 on 2023-03-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_filefield_remove_chat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
