# Generated by Django 4.1.6 on 2023-03-11 17:09

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_to),
        ),
    ]
